### ISSUE TITLE
Npm run dev doesn't work

### ISSUE THREAD

**Issue by K4R7IK** [viniciusmoreeira/nextjs-portfolio#1]
Hey, liked your portfolio. I was trying to my build my own version of it by customizing yours, but there are many deprecated dependencies and many more errors while trying to run `npm run dev`

Here's the output of the above command
```
 npm run dev

> my-portfolio@0.1.0 dev
> next dev

[ wait ]  starting the development server ...
[ info ]  waiting on http://localhost:3000 ...
Browserslist: caniuse-lite is outdated. Please run next command `npm update`
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/corrupter/Projects/nextjs-portfolio/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/corrupter/Projects/nextjs-portfolio/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/corrupter/Projects/nextjs-portfolio/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/corrupter/Projects/nextjs-portfolio/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/corrupter/Projects/nextjs-portfolio/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/corrupter/Projects/nextjs-portfolio/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/corrupter/Projects/nextjs-portfolio/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/corrupter/Projects/nextjs-portfolio/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/corrupter/Projects/nextjs-portfolio/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/home/corrupter/Projects/nextjs-portfolio/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/home/corrupter/Projects/nextjs-portfolio/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at processResource (/home/corrupter/Projects/nextjs-portfolio/node_modules/loader-runner/lib/LoaderRunner.js:208:3)
    at iteratePitchingLoaders (/home/corrupter/Projects/nextjs-portfolio/node_modules/loader-runner/lib/LoaderRunner.js:158:10)
    at iteratePitchingLoaders (/home/corrupter/Projects/nextjs-portfolio/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/corrupter/Projects/nextjs-portfolio/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/corrupter/Projects/nextjs-portfolio/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/corrupter/Projects/nextjs-portfolio/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/corrupter/Projects/nextjs-portfolio/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/corrupter/Projects/nextjs-portfolio/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/corrupter/Projects/nextjs-portfolio/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/corrupter/Projects/nextjs-portfolio/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/corrupter/Projects/nextjs-portfolio/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/corrupter/Projects/nextjs-portfolio/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/home/corrupter/Projects/nextjs-portfolio/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/home/corrupter/Projects/nextjs-portfolio/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at processResource (/home/corrupter/Projects/nextjs-portfolio/node_modules/loader-runner/lib/LoaderRunner.js:208:3)
    at iteratePitchingLoaders (/home/corrupter/Projects/nextjs-portfolio/node_modules/loader-runner/lib/LoaderRunner.js:158:10)
    at iteratePitchingLoaders (/home/corrupter/Projects/nextjs-portfolio/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/corrupter/Projects/nextjs-portfolio/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/corrupter/Projects/nextjs-portfolio/node_modules/webpack/lib/NormalModule.js:417:16)
    at /home/corrupter/Projects/nextjs-portfolio/node_modules/webpack/lib/NormalModule.js:452:10
    at /home/corrupter/Projects/nextjs-portfolio/node_modules/webpack/lib/NormalModule.js:323:13
    at /home/corrupter/Projects/nextjs-portfolio/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/corrupter/Projects/nextjs-portfolio/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/corrupter/Projects/nextjs-portfolio/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/corrupter/Projects/nextjs-portfolio/node_modules/next/dist/compiled/babel-loader/index.js:1:3586 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.16.1
```

If you could help me solve them, it would be a great help

**Comment by viniciusmoreria** [comment]
hi! thanks for letting me know, haven't touched this project in years :)
i just tried to run it again and its working for me as of node v16.16.0, can you try to downgrade your version? or maybe have a look into [this](https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported)

**Comment by K4R7IK** [comment]
Thanks i'll look into it.
